version: "3"

services:

  ditto-mqtt-bridge:
    image: jfeinauer/mqtt-to-iotdb-bridge:1.0.0-SNAPSHOT
    volumes:
      - "./config.json:/opt/service/config.json"
    depends_on:
      - iotdb

  plc4x-producer:
    image: jfeinauer/plc4x-to-ditto-producer:1.0.0-SNAPSHOT
    volumes:
      - "./config.json:/opt/service/config.json"

  iotdb:
    image: apache/iotdb:0.9.1-jre8
    expose:
      - "6667"
      - "31999"
      - "8181"
    ports:
      - "6667:6667"
      - "31999:31999"
      - "8181:8181"

  iotdb-grafana:
    image: jfeinauer/iotdb-grafana:0.9.3
    ports:
      - "8888:8888"
      - "4000:4000"
    environment:
      IOTDB_HOST: iotdb
      IOTDB_PORT: 6667
      IOTDB_USER: root
      IOTDB_PASSWORD: root
    depends_on:
      - iotdb

  grafana:
    build: ./grafana
    ports:
    - "3000:3000"
    depends_on:
      - iotdb-grafana