FROM arm32v7/adoptopenjdk:11-jre-hotspot
MAINTAINER Julian

CMD mkdir -p /opt/service
COPY maven/*.jar /opt/service/

EXPOSE 8080

ENTRYPOINT ["java", "-cp", "/opt/service/*", "org.pragmaticindustries.ditto.Plc4XMqttProducerMqtt"]
